name: Update Resolvers.txt

on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Download first 1000 entries from nameservers.txt
        run: |
          curl -s https://public-dns.info/nameservers.txt | head -n 10000 > nameservers_1000.txt
        continue-on-error: true # Continue even if there are fewer than 1000 entries

      - name: Run dnsvalidator and commit resolvers.txt
        env:
          DOCKER_IMAGE: wfnintr/dnsvalidator
        run: |
          # Pull the Docker image
          docker pull $DOCKER_IMAGE

          # Run dnsvalidator and generate resolvers.txt
          docker run --rm -v $PWD:/app $DOCKER_IMAGE -tL /app/nameservers_1000.txt -threads 50 -o /app/resolvers.txt -timeout 300

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git commit -m "resolvers.txt updated :robot:"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
